### ISSUE TITLE
How to run 😭

### ISSUE THREAD

**Issue by girish54321** [nt4f04uNd/sweyer#14]
Hey im trying to run your app is not working 
what im doing wrong 

<img width="226" alt="Screenshot 2021-06-20 at 6 41 36 PM" src="https://user-images.githubusercontent.com/47414322/122675516-6b2a6580-d1f7-11eb-91cf-3f3847321ccc.png">
<img width="922" alt="Screenshot 2021-06-20 at 6 43 49 PM" src="https://user-images.githubusercontent.com/47414322/122675521-754c6400-d1f7-11eb-99c1-bb3048f5e515.png">

`flutter doctor`

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by nt4f04uNd** [comment]
I'm not completely sure, but I suppose that you cannot run it because, while the app uses some firebase SDKs, I do not check the `google-services.json` into the source control. You could either:
* try adding your own one
* or try removing the SDKs at all (which I done in this commit for example https://github.com/nt4f04uNd/sweyer/commit/0e27a82a85f62c7d4ab91d2ffbba2b2544ca4498 to make a repro for some issue in the VSCode extension)

If you'd like to run 1.0.4 branch, I suppose you can't yet, since I have some stuff in git dependencies not yet pushed to origins

**Comment by girish54321** [comment]
Thanks, @nt4f04uNd will try your steps 👍
