### ISSUE TITLE
Any Updates?

### ISSUE THREAD

**Issue by prateekmedia** [nt4f04uNd/sweyer#8]
The app looks amazing but is still missing some implementations : 
+ Android x support
+ Latest flutter stable 1.22 or dev channel support
+ Albums are not clickable + they dont have cover art
+ Only available in Russian but not in English

I know its non commercial as you stated in the Readme but these features will make the app more reachable to wider range of audience

**Comment by nt4f04uNd** [comment]
@prateekmedia I have a lot of new stuff not pushed and just stored locally
I was planning the 1.0.1 release, but I don't have much time for it now, since I have a job. The commit will be huge and I want to polish the app and populate it with some features before pushing it
Hopefully, I'll make it in the next month with releasing the app to Google play

By the way a lot of the codebase will be similar to what you can already see in https://github.com/nt4f04uNd/nt4f04unds_widgets
This app is kinda playground for exploring Flutter features. I played around with some, written somewhat reusable code and separated into this library, as I wanted to use it in my job, and that's also the part that made it difficult to write the code further for me. Though as I said already, just wait for some time, I'll push it as soon as I can

**Comment by prateekmedia** [comment]
> @prateekmedia I have a lot of new stuff not pushed and just stored locally
> I was planning the 1.0.1 release, but I don't have much time for it now, since I have a job. The commit will be huge and I want to polish the app and populate it with some features before pushing it
> Hopefully, I'll make it in the next month with releasing the app to Google play
> 
> By the way a lot of the codebase will be similar to what you can already see in https://github.com/nt4f04uNd/nt4f04unds_widgets
> This app is kinda playground for exploring Flutter features. I played around with some, written somewhat reusable code and separated into this library, as I wanted to use it in my job, and that's also the part that made it difficult to write the code further for me. Though as I said already, just wait for some time, I'll push it as soon as I can

Please please support english as a language in it and russian as a localized language as it will also help other non-Russian speakers to use this app flawlessly

**Comment by prateekmedia** [comment]
@nt4f04uNd Ok found the way to make your app list when opening music using external application 

You should try the method given below in the post of so

https://stackoverflow.com/questions/51885459/flutter-how-to-let-a-file-be-opened-by-an-external-app-like-androids-implicit

**Comment by nt4f04uNd** [comment]
@prateekmedia i have a trouble with google play dev console, they rejected my id
i think i will pulush new version this weekend if all goes ok

re: opening files - i postpone this until next release (or maybe even next after next release)

**Comment by prateekmedia** [comment]
Ok then

**Comment by nt4f04uNd** [comment]
@prateekmedia enjoy https://github.com/nt4f04uNd/sweyer/releases/tag/1.0.1
list of new features is in https://github.com/nt4f04uNd/sweyer/blob/master/CHANGELOG.md
